# Generated by Django 3.0.8 on 2020-07-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200705_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
